version: '3.8'

services:
  train-booking:
    image: ghcr.io/taelyon/train-booking:latest
    container_name: train_booking_bot
    restart: unless-stopped
    ports:
      # 외부접속포트:내부포트
      - "5010:5001"
    volumes:
      # 설정 및 인증 정보 보존을 위한 환경변수 파일 매핑
      # NAS의 프로젝트 폴더 내에 .env 파일을 미리 준비해 두어야 합니다.
      - ./.env:/app/.env
      # 로그 파일과 영속성 데이터를 NAS 바깥으로 빼내기 위한 설정
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - TZ=Asia/Seoul
